<?php

class Constants 
{
    public const  PHYLUM = ['Tracheophyta'];

    public const CLASSES = ['Magnoliopsida'];
    
    public const ORDER = ['Caryophyllales'];
    
    public const FAMILY = ['Cactaceae'];
    
    public const GENUS = ['Acanthocalycium',
        'Acanthocereus',
        'Acharagma',
        'Airampoa',
        'Aporocactus',
        'Aporophyllum',
        'Ariocarpus',
        'Armatocereus',
        'Arrojadoa',
        'Arthrocereus',
        'Astrophytum',
        'Austrocactus',
        'Austrocephalocereus',
        'Austrocylindropuntia',
        'Aylostera',
        'Aztekium',
        'Aztekonia',
        'Backebergia',
        'Bergerocactus',
        'Blossfeldia',
        'Borzicactus',
        'Borzipostoa',
        'Brachycereus',
        'Brasilicactus',
        'Brasilicereus',
        'Brasiliopuntia',
        'Bridgesia',
        'Browningia',
        'Cactus',
        'Calymmanthium',
        'Carnegiea',
        'Cassyta',
        'Castellanosia',
        'Cephalocereus',
        'Cephalocleistocactus',
        'Cephalomamillaria',
        'Cereus',
        'Chamaebivia',
        'Cintia',
        'Cipocereus',
        'Cleistocactus',
        'Coleocephalocereus',
        'Consolea',
        'Copiapoa',
        'Corryocactus',
        'Corynopuntia',
        'Coryphantha',
        'Cumarinia',
        'Cumulopuntia',
        'Cylindropuntia',
        'Deamia',
        'Dendrocereus',
        'Denmoza',
        'Discocactus',
        'Disocactus',
        'Disoselenicereus',
        'Echinocactus',
        'Echinocereus',
        'Echinofossulocactus',
        'Echinomastus',
        'Echinopsis',
        'Epiphyllum',
        'Epithelantha',
        'Eriosyce',
        'Escobaria',
        'Escontria',
        'Espostoa',
        'Espostoopsis',
        'Eulychnia',
        'Facheiroa',
        'Ferobergia',
        'Ferocactus',
        'Frailea',
        'Geohintonia',
        'Grusonia',
        'Gymnocalycium',
        'Haageocereus',
        'Haagespostoa',
        'Hariota',
        'Harrisia',
        'Harrisinopsis',
        'Hatiora',
        'Heliocereus',
        'Hylocereus',
        'Islaya',
        'Isolatocereus',
        'Jasminocereus',
        'Kadenicarpus',
        'Kimnachia',
        'Krainzia',
        'Lasiocereus',
        'Lemaireocereus',
        'Leocereus',
        'Lepismium',
        'Leptocereus',
        'Leptocladia',
        'Leuchtenbergia',
        'Leucostele',
        'Leuenbergeria',
        'Lobivia',
        'Lophocereus',
        'Lophophora',
        'Loxanthocereus',
        'Lymanbensonia',
        'Maihuenia',
        'Maihueniopsis',
        'Malacocarpus',
        'Mammillaria',
        'Mammilloydia',
        'Marginatocereus',
        'Marniera',
        'Marshallocereus',
        'Matucana',
        'Maturoya',
        'Melocactus',
        'Micranthocereus',
        'Micropuntia',
        'Mila',
        'Miqueliopuntia',
        'Mirabella',
        'Monvillea',
        'Myrtgerocactus',
        'Myrtillenocereus',
        'Myrtillocactus',
        'Neobesseya',
        'Neobuxbaumia',
        'Neochilenia',
        'Neolloydia',
        'Neolobivia',
        'Neomammillaria',
        'Neoporteria',
        'Neoraimondia',
        'Neowerdermannia',
        'Nopalea',
        'Notocactus',
        'Nyctocereus',
        'Obregonia',
        'Oehmea',
        'Opuntia',
        'Oreocereus',
        'Oroya',
        'Ortegocactus',
        'Pacherocactus',
        'Pachgerocereus',
        'Pachycereus',
        'Parodia',
        'Pediocactus',
        'Pelecyphora',
        'Peniocereus',
        'Pereskia',
        'Pereskiopsis',
        'Pfeiffera',
        'Pierrebraunia',
        'Pilocereus',
        'Pilosocereus',
        'Platyopuntia',
        'Polaskia',
        'Porfiria',
        'Praecereus',
        'Pseudoacanthocereus',
        'Pseudomitrocereus',
        'Pseudopilocereus',
        'Pseudorhipsalis',
        'Pseudosolisia',
        'Pterocactus',
        'Pterocereus',
        'Puebloa',
        'Puna',
        'Punotia',
        'Pygmaeocereus',
        'Pyrrhocactus',
        'Quiabentia',
        'Rapicactus',
        'Rauhocereus',
        'Rebutia',
        'Rhipsalis',
        'Rhodocactus',
        'Rimacactus',
        'Ritterocereus',
        'Salmiopuntia',
        'Samaipaticereus',
        'Schlumbergera',
        'Sclerocactus',
        'Selenicereus',
        'Seleniporocactus',
        'Siccobaccatus',
        'Solisia',
        'Stenocactus',
        'Stenocereus',
        'Stephanocereus',
        'Stetsonia',
        'Stromatocarpus',
        'Strombocactus',
        'Strophocactus',
        'Sulcorebutia',
        'Tacinga',
        'Tephrocactus',
        'Thelocactus',
        'Thelocephala',
        'Thrixanthocereus',
        'Torreycactus',
        'Trichocereus',
        'Trichoechinopsis',
        'Trichomoza',
        'Tunilla',
        'Turbinicarpus',
        'Uebelmannia',
        'Weberbauerocereus',
        'Weberocereus',
        'Weingartia',
        'Werckleocereus',
        'Wigginsia',
        'Xiquexique',
        'Yavia',
        'Yungasocereus',
        'Zygocactus',
    ];
    
    public const SCIENTFICNAME = [
        'Acanthocalycium ferrarii', 
        'Acanthocalycium klimpelianum', 
        'Acanthocalycium leucanthum', 
        'Acanthocalycium rhodotrichum', 
        'Acanthocalycium spiniflorum', 
        'Acanthocalycium thionanthum', 
        'Acanthocereus atropurpureus', 
        'Acanthocereus canoensis', 
        'Acanthocereus castellae', 
        'Acanthocereus chiapensis', 
        'Acanthocereus cuixmalensis', 
        'Acanthocereus fosterianus', 
        'Acanthocereus haackeanus', 
        'Acanthocereus hesperius', 
        'Acanthocereus hirschtianus', 
        'Acanthocereus macdougallii', 
        'Acanthocereus maculatus', 
        'Acanthocereus oaxacensis', 
        'Acanthocereus rosei', 
        'Acanthocereus tepalcatepecanus', 
        'Acanthocereus tetragonus', 
        'Acharagma aguirreana', 
        'Acharagma huasteca', 
        'Acharagma roseanum', 
        'Aporocactus flagelliformis', 
        'Aporocactus martianus', 
        'Ariocarpus agavoides', 
        'Ariocarpus fissuratus', 
        'Ariocarpus kotschoubeyanus', 
        'Ariocarpus retusus', 
        'Ariocarpus scaphirostris', 
        'Ariocarpus trigonus', 
        'Armatocereus cartwrightianus', 
        'Armatocereus godingianus', 
        'Armatocereus laetus', 
        'Armatocereus matucanensis', 
        'Armatocereus procerus', 
        'Armatocereus rauhii', 
        'Armatocereus riomajensis', 
        'Arrojadoa albiflora', 
        'Arrojadoa dinae', 
        'Arrojadoa marylanae', 
        'Arrojadoa marylaniae', 
        'Arrojadoa penicillata', 
        'Arrojadoa rhodantha', 
        'Arthrocereus glaziovii', 
        'Arthrocereus melanurus', 
        'Arthrocereus rondonianus', 
        'Arthrocereus spinosissimus', 
        'Astrophytum asterias', 
        'Astrophytum capricorne', 
        'Astrophytum caput-medusae', 
        'Astrophytum coahuilense', 
        'Astrophytum myriostigma', 
        'Astrophytum ornatum', 
        'Austrocactus bertinii', 
        'Austrocactus ferrarii', 
        'Austrocactus hibernus', 
        'Austrocactus patagonicus', 
        'Austrocactus pauxillus', 
        'Austrocactus philippii', 
        'Austrocactus spiniflorus', 
        'Austrocylindropuntia cylindrica', 
        'Austrocylindropuntia floccosa', 
        'Austrocylindropuntia pachypus', 
        'Austrocylindropuntia shaferi', 
        'Austrocylindropuntia subulata', 
        'Austrocylindropuntia vestita', 
        'Aylostera albopectinata', 
        'Aylostera azurduyensis', 
        'Aylostera deminuta', 
        'Aylostera einsteinii', 
        'Aylostera eos', 
        'Aylostera malochii', 
        'Aylostera mamillosa', 
        'Aylostera pygmaea', 
        'Aylostera tuberosa', 
        'Aztekium ritteri', 
        'Aztekium valdezii', 
        'Aztekonia hintonii', 
        'Bergerocactus emoryi', 
        'Blossfeldia liliputana', 
        'Borzicactus acanthurus', 
        'Borzicactus aureispinus', 
        'Borzicactus fieldianus', 
        'Borzicactus hoffmannii', 
        'Borzicactus hystrix', 
        'Borzicactus icosagonus', 
        'Borzicactus jajoianus', 
        'Borzicactus leonensis', 
        'Borzicactus longiserpens', 
        'Borzicactus neoroezlii', 
        'Borzicactus pachycladus', 
        'Borzicactus plagiostoma', 
        'Borzicactus samaipatanus', 
        'Borzicactus sepium', 
        'Borzicactus sextonianus', 
        'Borzicactus straussii', 
        'Borzicactus sulcifer', 
        'Borzicactus tenuiserpens', 
        'Borzicactus tominensis', 
        'Borzicactus wrightii', 
        'Borzicactus xylorhizus', 
        'Brachycereus nesioticus', 
        'Brasilicereus markgrafii', 
        'Brasilicereus phaeacanthus', 
        'Brasiliopuntia brasiliensis', 
        'Brasiliopuntia schickendantzii', 
        'Brasiliopuntia schulzii', 
        'Browningia altissima', 
        'Browningia caineana', 
        'Browningia candelaris', 
        'Browningia chlorocarpa', 
        'Browningia columnaris', 
        'Browningia hernandezii', 
        'Browningia hertlingiana', 
        'Browningia macracantha', 
        'Browningia microsperma', 
        'Browningia pilleifera', 
        'Browningia utcubambensis', 
        'Cactus alternatus', 
        'Cactus brunneus', 
        'Cactus maculatus', 
        'Cactus peruvianus', 
        'Calymmanthium substerile', 
        'Carnegiea gigantea', 
        'Cephalocereus apicicephalium', 
        'Cephalocereus columna-trajani', 
        'Cephalocereus exerens', 
        'Cephalocereus nizandensis', 
        'Cephalocereus parvispinus', 
        'Cephalocereus senilis', 
        'Cephalocleistocactus ritteri', 
        'Cereus aethiops', 
        'Cereus albicaulis', 
        'Cereus albispinus', 
        'Cereus argentinensis', 
        'Cereus aureus', 
        'Cereus babosus', 
        'Cereus beckmannii', 
        'Cereus bicolor', 
        'Cereus caudatus', 
        'Cereus colosseus', 
        'Cereus comarapanus', 
        'Cereus devauxii', 
        'Cereus fernambucensis', 
        'Cereus forbesii', 
        'Cereus formosus', 
        'Cereus fricii', 
        'Cereus glaucescens', 
        'Cereus glaucus', 
        'Cereus gracilis', 
        'Cereus haageanus', 
        'Cereus hankeanus', 
        'Cereus hermannianus', 
        'Cereus hertrichianus', 
        'Cereus hexagonus', 
        'Cereus hildmannianus', 
        'Cereus hildmannii', 
        'Cereus horrispinus', 
        'Cereus houlletii', 
        'Cereus huilunchu', 
        'Cereus humilis', 
        'Cereus insularis', 
        'Cereus jamacaru', 
        'Cereus jugatiflorus', 
        'Cereus krapovickianus', 
        'Cereus kroenleinii', 
        'Cereus lamprospermus', 
        'Cereus lanosus', 
        'Cereus lasianthus', 
        'Cereus lepidotus', 
        'Cereus magnus', 
        'Cereus malletianus', 
        'Cereus maynardii', 
        'Cereus mirabella', 
        'Cereus monvilleanus', 
        'Cereus mortensenii', 
        'Cereus nigrispinus', 
        'Cereus paraguayensis', 
        'Cereus phatnospermus', 
        'Cereus pierre-braunianus', 
        'Cereus pitahaya', 
        'Cereus platygonus', 
        'Cereus pterogonus', 
        'Cereus repandus', 
        'Cereus resupinatus', 
        'Cereus rigidispinus', 
        'Cereus saddianus', 
        'Cereus simonii', 
        'Cereus smithianus', 
        'Cereus spegazzinii', 
        'Cereus spinosus', 
        'Cereus stenogonus', 
        'Cereus tacuaralensis', 
        'Cereus tenellus', 
        'Cereus torulosus', 
        'Cereus trigonodendron', 
        'Cereus tripteris', 
        'Cereus triqueter', 
        'Cereus vargasianus', 
        'Cereus viridflorus', 
        'Cereus yungasensis', 
        'Cipocereus bradei', 
        'Cipocereus crassisepalus', 
        'Cipocereus laniflorus', 
        'Cipocereus minensis', 
        'Cipocereus pusilliflorus', 
        'Cleistocactus baumannii', 
        'Cleistocactus brookeae', 
        'Cleistocactus brookei', 
        'Cleistocactus candelilla', 
        'Cleistocactus ferrarii', 
        'Cleistocactus hyalacanthus', 
        'Cleistocactus laniceps', 
        'Cleistocactus luribayensis', 
        'Cleistocactus morawetzianus', 
        'Cleistocactus parviflorus', 
        'Cleistocactus pungens', 
        'Cleistocactus pycnacanthus', 
        'Cleistocactus reae', 
        'Cleistocactus rojoi', 
        'Cleistocactus smaragdiflorus', 
        'Cleistocactus tupizensis', 
        'Coleocephalocereus aureus', 
        'Coleocephalocereus braunii', 
        'Coleocephalocereus buxbaumianus', 
        'Coleocephalocereus diersianus', 
        'Coleocephalocereus fluminensis', 
        'Coleocephalocereus goebelianus', 
        'Coleocephalocereus pluricostatus', 
        'Coleocephalocereus purpureus', 
        'Consolea macracantha', 
        'Consolea moniliformis', 
        'Consolea spinosissima', 
        'Copiapoa ahremephiana', 
        'Copiapoa angustiflora', 
        'Copiapoa boliviana', 
        'Copiapoa calderana', 
        'Copiapoa calderiana', 
        'Copiapoa cinerascens', 
        'Copiapoa cinerea', 
        'Copiapoa coquimbana', 
        'Copiapoa dealbata', 
        'Copiapoa decorticans', 
        'Copiapoa echinata', 
        'Copiapoa echinoides', 
        'Copiapoa eremophila', 
        'Copiapoa grandiflora', 
        'Copiapoa griseoviolacea', 
        'Copiapoa humilis', 
        'Copiapoa hypogaea', 
        'Copiapoa intermedia', 
        'Copiapoa krainziana', 
        'Copiapoa laui', 
        'Copiapoa leonensis', 
        'Copiapoa longistaminea', 
        'Copiapoa marginata', 
        'Copiapoa megarhiza', 
        'Copiapoa rarissima', 
        'Copiapoa rupestris', 
        'Copiapoa serpentisulcata', 
        'Copiapoa solaris', 
        'Corryocactus apiciflorus', 
        'Corryocactus aureus', 
        'Corryocactus ayacuchoensis', 
        'Corryocactus brachypetalus', 
        'Corryocactus brevistylus', 
        'Corryocactus chachapoyensis', 
        'Corryocactus charazanensis', 
        'Corryocactus dillonii', 
        'Corryocactus erectus', 
        'Corryocactus melanotrichus', 
        'Corryocactus pulquiensis', 
        'Corryocactus pulquinensis', 
        'Corryocactus quadrangularis', 
        'Corryocactus quadranularis', 
        'Corryocactus serpens', 
        'Corryocactus squarrosus', 
        'Corryocactus tarijensis', 
        'Corynopuntia aggeria', 
        'Corynopuntia bulbispina', 
        'Corynopuntia clavata', 
        'Corynopuntia deinacantha', 
        'Corynopuntia emoryi', 
        'Corynopuntia grahamii', 
        'Corynopuntia invicta', 
        'Corynopuntia kunzei', 
        'Corynopuntia marenae', 
        'Corynopuntia moelleri', 
        'Corynopuntia parishii', 
        'Corynopuntia reflexispina', 
        'Corynopuntia robertsii', 
        'Corynopuntia schottii', 
        'Corynopuntia vilis', 
        'Coryphantha clavata', 
        'Coryphantha compacta', 
        'Coryphantha delaetiana', 
        'Coryphantha delicata', 
        'Coryphantha difficilis', 
        'Coryphantha durangensis', 
        'Coryphantha echinoidea', 
        'Coryphantha echinus', 
        'Coryphantha elephantidens', 
        'Coryphantha erecta', 
        'Coryphantha georgii', 
        'Coryphantha glanduligera', 
        'Coryphantha glassii', 
        'Coryphantha gracilis', 
        'Coryphantha guerkeana', 
        'Coryphantha hintoniorum', 
        'Coryphantha jalpanensis', 
        'Coryphantha kracikii', 
        'Coryphantha longicornis', 
        'Coryphantha macromeris', 
        'Coryphantha maiz-tablasensis', 
        'Coryphantha neglecta', 
        'Coryphantha nickelsae', 
        'Coryphantha nickelsiae', 
        'Coryphantha octacantha', 
        'Coryphantha ottonis', 
        'Coryphantha pallida', 
        'Coryphantha poselgeriana', 
        'Coryphantha potosiana', 
        'Coryphantha pseudechinus', 
        'Coryphantha pseudoechinus', 
        'Coryphantha pseudonickelsiae', 
        'Coryphantha pulleineana', 
        'Coryphantha pycnacantha', 
        'Coryphantha radians', 
        'Coryphantha ramillosa', 
        'Coryphantha recurvata', 
        'Coryphantha retusa', 
        'Coryphantha robustispina', 
        'Coryphantha salinensis', 
        'Coryphantha sulcata', 
        'Coryphantha tripugionacantha', 
        'Coryphantha vaupeliana', 
        'Coryphantha vogtherriana', 
        'Coryphantha werdermannii', 
        'Coryphantha wohlschlageri', 
        'Cumarinia odorata', 
        'Cumulopuntia boliviana', 
        'Cumulopuntia chichensis', 
        'Cumulopuntia iturbicola', 
        'Cumulopuntia leucophaea', 
        'Cumulopuntia pentlandii', 
        'Cumulopuntia sphaerica', 
        'Cylindropuntia abyssi', 
        'Cylindropuntia acanthocarpa', 
        'Cylindropuntia alcahes', 
        'Cylindropuntia anteojoensis', 
        'Cylindropuntia antoniae', 
        'Cylindropuntia arbuscula', 
        'Cylindropuntia bigelowii', 
        'Cylindropuntia californica', 
        'Cylindropuntia campii', 
        'Cylindropuntia caribaea', 
        'Cylindropuntia cedrosensis', 
        'Cylindropuntia cholla', 
        'Cylindropuntia chuckwallensis', 
        'Cylindropuntia congesta', 
        'Cylindropuntia davisii', 
        'Cylindropuntia delgadilloana', 
        'Cylindropuntia deserta', 
        'Cylindropuntia echinocarpa', 
        'Cylindropuntia fosbergii', 
        'Cylindropuntia fulgida', 
        'Cylindropuntia ganderi', 
        'Cylindropuntia grantiorum', 
        'Cylindropuntia hystrix', 
        'Cylindropuntia imbricata', 
        'Cylindropuntia kelvinensis', 
        'Cylindropuntia kleiniae', 
        'Cylindropuntia leptocaulis', 
        'Cylindropuntia libertadensis', 
        'Cylindropuntia lindsayi', 
        'Cylindropuntia molesta', 
        'Cylindropuntia multigeniculata', 
        'Cylindropuntia munzii', 
        'Cylindropuntia neoarbuscula', 
        'Cylindropuntia prolifera', 
        'Cylindropuntia ramosissima', 
        'Cylindropuntia rosea', 
        'Cylindropuntia sanfelipensis', 
        'Cylindropuntia santamaria', 
        'Cylindropuntia spinosior', 
        'Cylindropuntia tesajo', 
        'Cylindropuntia tetracantha', 
        'Cylindropuntia thurberi', 
        'Cylindropuntia tunicata', 
        'Cylindropuntia versicolor', 
        'Cylindropuntia viridiflora', 
        'Cylindropuntia vivipara', 
        'Cylindropuntia waltoniorum', 
        'Cylindropuntia whipplei', 
        'Cylindropuntia wolfii', 
        'Deamia chontalensis', 
        'Deamia montalvoae', 
        'Deamia testudo', 
        'Denmoza rhodacantha', 
        'Discocactus bahiensis', 
        'Discocactus boliviensis', 
        'Discocactus catingicola', 
        'Discocactus diersianus', 
        'Discocactus fariae-peresii', 
        'Discocactus hartmannii', 
        'Discocactus heptacanthus', 
        'Discocactus horstii', 
        'Discocactus lindanus', 
        'Discocactus placentiformis', 
        'Discocactus pseudoinsignis', 
        'Discocactus zehnteri', 
        'Discocactus zehntneri', 
        'Disocactus ackermannii', 
        'Disocactus anguliger', 
        'Disocactus biformis', 
        'Disocactus crenatus', 
        'Disocactus eichlamii', 
        'Disocactus hybridus', 
        'Disocactus kimnachii', 
        'Disocactus lepidocarpus', 
        'Disocactus lodei', 
        'Disocactus macdougallii', 
        'Disocactus macranthus', 
        'Disocactus mallisonii', 
        'Disocactus nelsonii', 
        'Disocactus phyllanthoides', 
        'Disocactus quezaltecus', 
        'Disocactus salvadorensis', 
        'Disocactus speciosus', 
        'Echinocactus cylindricus', 
        'Echinocactus debilispinus', 
        'Echinocactus grusonii', 
        'Echinocactus horizonthalonius', 
        'Echinocactus lancifer', 
        'Echinocactus megapotamicus', 
        'Echinocactus parryi', 
        'Echinocactus pepinianus', 
        'Echinocactus platyacanthus', 
        'Echinocactus polycephalus', 
        'Echinocactus pulverulentus', 
        'Echinocactus sulcatus', 
        'Echinocactus texensis', 
        'Echinocactus trollietii', 
        'Echinocereus acanthosetus', 
        'Echinocereus adustus', 
        'Echinocereus arizonicus', 
        'Echinocereus bakeri', 
        'Echinocereus barthelowanus', 
        'Echinocereus barthelowianus', 
        'Echinocereus berlandieri', 
        'Echinocereus blumii', 
        'Echinocereus bonkerae', 
        'Echinocereus brandegeei', 
        'Echinocereus bristolii', 
        'Echinocereus chisoensis', 
        'Echinocereus chisosensis', 
        'Echinocereus cinerascens', 
        'Echinocereus coccineus', 
        'Echinocereus conglomeratus', 
        'Echinocereus dasyacanthus', 
        'Echinocereus engelmannii', 
        'Echinocereus enneacanthus', 
        'Echinocereus fasciculatus', 
        'Echinocereus felixianus', 
        'Echinocereus fendleri', 
        'Echinocereus ferreiranus', 
        'Echinocereus ferreirianus', 
        'Echinocereus grandis', 
        'Echinocereus klapperi', 
        'Echinocereus knippelianus', 
        'Echinocereus laui', 
        'Echinocereus ledingii', 
        'Echinocereus leucanthus', 
        'Echinocereus lindsayorum', 
        'Echinocereus llanurensis', 
        'Echinocereus longisetus', 
        'Echinocereus mamillosus', 
        'Echinocereus mapimiensis', 
        'Echinocereus maritimus', 
        'Echinocereus marksianus', 
        'Echinocereus mombergerianus', 
        'Echinocereus nicholii', 
        'Echinocereus nivosus', 
        'Echinocereus ochoterenae', 
        'Echinocereus ortegae', 
        'Echinocereus palmeri', 
        'Echinocereus pamanesii', 
        'Echinocereus pamanesiorum', 
        'Echinocereus papillosus', 
        'Echinocereus parkeri', 
        'Echinocereus pectinatus', 
        'Echinocereus penicilliformis', 
        'Echinocereus pensilis', 
        'Echinocereus pentalophus', 
        'Echinocereus platyacanthus', 
        'Echinocereus polyacanthus', 
        'Echinocereus polycephalus', 
        'Echinocereus poselgeri', 
        'Echinocereus primolanatus', 
        'Echinocereus princeps', 
        'Echinocereus pringlei', 
        'Echinocereus pseudopectinatus', 
        'Echinocereus pulchellus', 
        'Echinocereus reichenbachii', 
        'Echinocereus relictus', 
        'Echinocereus rigidissimus', 
        'Echinocereus roetteri', 
        'Echinocereus russanthus', 
        'Echinocereus salm-dyckianus', 
        'Echinocereus scheeri', 
        'Echinocereus schereri', 
        'Echinocereus schmollii', 
        'Echinocereus sciurus', 
        'Echinocereus scopulorum', 
        'Echinocereus sharpii', 
        'Echinocereus spinigemmatus', 
        'Echinocereus stolonifer', 
        'Echinocereus stoloniferus', 
        'Echinocereus stramineus', 
        'Echinocereus subinermis', 
        'Echinocereus tamaulipensis', 
        'Echinocereus trichacanthus', 
        'Echinocereus triglochidiatus', 
        'Echinocereus viereckii', 
        'Echinocereus viridiflorus', 
        'Echinocereus websterianus', 
        'Echinocereus weinbergii', 
        'Echinocereus yavapaiensis', 
        'Echinofossulocactus rectospinus', 
        'Echinofossulocactus tegelbergii', 
        'Echinomastus kakui', 
        'Echinopsis acchaensis', 
        'Echinopsis albispinosa', 
        'Echinopsis ancistrophora', 
        'Echinopsis angelesii', 
        'Echinopsis apiculata', 
        'Echinopsis arachnacantha', 
        'Echinopsis arboricola', 
        'Echinopsis atacamensis', 
        'Echinopsis aurea', 
        'Echinopsis ayopayana', 
        'Echinopsis backebergii', 
        'Echinopsis bonnieae', 
        'Echinopsis bridgesii', 
        'Echinopsis cabrerae', 
        'Echinopsis caineana', 
        'Echinopsis calochlora', 
        'Echinopsis calorubra', 
        'Echinopsis camarguensis', 
        'Echinopsis candicans', 
        'Echinopsis caulescens', 
        'Echinopsis chamaecereus', 
        'Echinopsis chereauniana', 
        'Echinopsis chiloensis', 
        'Echinopsis chrysantha', 
        'Echinopsis chrysochete', 
        'Echinopsis cinnabarina', 
        'Echinopsis clavatus', 
        'Echinopsis cuzcoensis', 
        'Echinopsis densispina', 
        'Echinopsis deserticola', 
        'Echinopsis elegans', 
        'Echinopsis erectispina', 
        'Echinopsis famatinensis', 
        'Echinopsis ferox', 
        'Echinopsis formosa', 
        'Echinopsis glauca', 
        'Echinopsis haematantha', 
        'Echinopsis hahniana', 
        'Echinopsis hertrichiana', 
        'Echinopsis huascha', 
        'Echinopsis jajoana', 
        'Echinopsis jajoiana', 
        'Echinopsis krahn-juckeri', 
        'Echinopsis lagemannii', 
        'Echinopsis lageniformis', 
        'Echinopsis lamprochlora', 
        'Echinopsis lateritia', 
        'Echinopsis mamillosa', 
        'Echinopsis marsoneri', 
        'Echinopsis maximiliana', 
        'Echinopsis mirabilis', 
        'Echinopsis muelleri', 
        'Echinopsis nigerrima', 
        'Echinopsis nigripilis', 
        'Echinopsis obrepanda', 
        'Echinopsis oligotricha', 
        'Echinopsis oxygona', 
        'Echinopsis pachanoi', 
        'Echinopsis pampana', 
        'Echinopsis pamparuizii', 
        'Echinopsis pentlandii', 
        'Echinopsis peruvianus', 
        'Echinopsis pseudocandicans', 
        'Echinopsis pugionacantha', 
        'Echinopsis quadratiumbonata', 
        'Echinopsis rojasii', 
        'Echinopsis rowleyi', 
        'Echinopsis saltensis', 
        'Echinopsis schickendantzii', 
        'Echinopsis schieliana', 
        'Echinopsis serpentina', 
        'Echinopsis spachiana', 
        'Echinopsis stilowiana', 
        'Echinopsis strigosa', 
        'Echinopsis tacaquirensis', 
        'Echinopsis tarijensis', 
        'Echinopsis tegeleriana', 
        'Echinopsis terscheckii', 
        'Echinopsis thelegona', 
        'Echinopsis thelegonoides', 
        'Echinopsis tiegeliana', 
        'Echinopsis trichosa', 
        'Echinopsis tubiflora', 
        'Echinopsis tucumanensis', 
        'Echinopsis tunariensis', 
        'Echinopsis vasquezii', 
        'Echinopsis volliana', 
        'Echinopsis walteri', 
        'Echinopsis werdermanniana', 
        'Echinopsis yuquina', 
        'Epiphyllum angulifer', 
        'Epiphyllum baueri', 
        'Epiphyllum cartagense', 
        'Epiphyllum floribundum', 
        'Epiphyllum grandilobum', 
        'Epiphyllum hookeri', 
        'Epiphyllum laui', 
        'Epiphyllum opuntioides', 
        'Epiphyllum oxypetalum', 
        'Epiphyllum phyllanthus', 
        'Epiphyllum pumilum', 
        'Epiphyllum thomasianum', 
        'Epithelantha bokei', 
        'Epithelantha cryptica', 
        'Epithelantha greggii', 
        'Epithelantha ilariae', 
        'Epithelantha micromeris', 
        'Epithelantha pachyrhiza', 
        'Epithelantha polycephala', 
        'Epithelantha potosina', 
        'Epithelantha pulchra', 
        'Epithelantha spinosior', 
        'Eriosyce aerocarpa', 
        'Eriosyce andreaeana', 
        'Eriosyce armata', 
        'Eriosyce aspillagae', 
        'Eriosyce atroviridis', 
        'Eriosyce aurata', 
        'Eriosyce bulbocalyx', 
        'Eriosyce calderana', 
        'Eriosyce calderiana', 
        'Eriosyce caligophila', 
        'Eriosyce castanea', 
        'Eriosyce chilensis', 
        'Eriosyce clavata', 
        'Eriosyce coimasensis', 
        'Eriosyce confinis', 
        'Eriosyce crispa', 
        'Eriosyce curvispina', 
        'Eriosyce duripulpa', 
        'Eriosyce elquiensis', 
        'Eriosyce engleri', 
        'Eriosyce esmeraldana', 
        'Eriosyce fankhauseri', 
        'Eriosyce fulva', 
        'Eriosyce garaventae', 
        'Eriosyce glabrescens', 
        'Eriosyce heinrichiana', 
        'Eriosyce iquiquensis', 
        'Eriosyce islayensis', 
        'Eriosyce krausii', 
        'Eriosyce kunzei', 
        'Eriosyce limariensis', 
        'Eriosyce litoralis', 
        'Eriosyce malleolata', 
        'Eriosyce marksiana', 
        'Eriosyce megacarpa', 
        'Eriosyce napina', 
        'Eriosyce nigrihorrida', 
        'Eriosyce occulta', 
        'Eriosyce odieri', 
        'Eriosyce paucicostata', 
        'Eriosyce recondita', 
        'Eriosyce riparia', 
        'Eriosyce rodentiophila', 
        'Eriosyce senilis', 
        'Eriosyce simulans', 
        'Eriosyce sociabilis', 
        'Eriosyce spectabilis', 
        'Eriosyce spinosior', 
        'Eriosyce strausiana', 
        'Eriosyce subgibbosa', 
        'Eriosyce taltalensis', 
        'Eriosyce tenebrica', 
        'Eriosyce umadeave', 
        'Eriosyce villicumensis', 
        'Eriosyce villosa', 
        'Eriosyce wagenknechtii', 
        'Escobaria abdita', 
        'Escobaria alversonii', 
        'Escobaria chihuahuensis', 
        'Escobaria cubensis', 
        'Escobaria dasyacantha', 
        'Escobaria duncanii', 
        'Escobaria emskoetteriana', 
        'Escobaria hesteri', 
        'Escobaria laredoi', 
        'Escobaria minima', 
        'Escobaria missouriensis', 
        'Escobaria robbinsorum', 
        'Escobaria sneedii', 
        'Escobaria tuberculosa', 
        'Escobaria vivipara', 
        'Escobaria zilziana', 
        'Escontria chiotilla', 
        'Espostoa blossfeldiorum', 
        'Espostoa calva', 
        'Espostoa frutescens', 
        'Espostoa guentheri', 
        'Espostoa hylaea', 
        'Espostoa lanata', 
        'Espostoa melanostele', 
        'Espostoa mirabilis', 
        'Espostoa senilis', 
        'Espostoa superba', 
        'Espostoopsis dybowskii', 
        'Eulychnia acida', 
        'Eulychnia aricensis', 
        'Eulychnia breviflora', 
        'Eulychnia castanea', 
        'Eulychnia coquimbana', 
        'Eulychnia iquiquensis', 
        'Eulychnia saint-pieana', 
        'Facheiroa cephaliomelana', 
        'Facheiroa squamosa', 
        'Facheiroa ulei', 
        'Ferocactus alamosanus', 
        'Ferocactus chrysacanthus', 
        'Ferocactus cylindraceus', 
        'Ferocactus diguetii', 
        'Ferocactus echidne', 
        'Ferocactus emoryi', 
        'Ferocactus flavovirens', 
        'Ferocactus fordii', 
        'Ferocactus glaucescens', 
        'Ferocactus gracilis', 
        'Ferocactus haematacanthus', 
        'Ferocactus hamatacanthus', 
        'Ferocactus histrix', 
        'Ferocactus johnstonianus', 
        'Ferocactus latispinus', 
        'Ferocactus lindsayi', 
        'Ferocactus macrodiscus', 
        'Ferocactus peninsulae', 
        'Ferocactus pilosus', 
        'Ferocactus pottsii', 
        'Ferocactus robustus', 
        'Ferocactus schwarzii', 
        'Ferocactus viridescens', 
        'Ferocactus wislizenii', 
        'Frailea alexandri', 
        'Frailea angelesiae', 
        'Frailea atrobella', 
        'Frailea buenekeri', 
        'Frailea castanea', 
        'Frailea cataphracta', 
        'Frailea chiquitana', 
        'Frailea curvispina', 
        'Frailea gracillima', 
        'Frailea mammifera', 
        'Frailea phaeodisca', 
        'Frailea pseudograhliana', 
        'Frailea pseudopulcherrima', 
        'Frailea pumila', 
        'Frailea pygmaea', 
        'Frailea schilinzkyana', 
        'Frailea stockingeri', 
        'Geohintonia mexicana', 
        'Grusonia bradtiana', 
        'Grusonia parishiorum', 
        'Gymnocactus roseiflorus', 
        'Gymnocalycium affine', 
        'Gymnocalycium albiareolatum', 
        'Gymnocalycium alboareolatum', 
        'Gymnocalycium amerhauseri', 
        'Gymnocalycium andreae', 
        'Gymnocalycium anisitsii', 
        'Gymnocalycium baldianum', 
        'Gymnocalycium bayrianum', 
        'Gymnocalycium bruchii', 
        'Gymnocalycium calochlorum', 
        'Gymnocalycium campestre', 
        'Gymnocalycium capillaense', 
        'Gymnocalycium capillense', 
        'Gymnocalycium carminanthum', 
        'Gymnocalycium castellanosii', 
        'Gymnocalycium chiquitanum', 
        'Gymnocalycium coloradense', 
        'Gymnocalycium denudatum', 
        'Gymnocalycium erinaceum', 
        'Gymnocalycium esperanzae', 
        'Gymnocalycium eurypleurum', 
        'Gymnocalycium friedrichii', 
        'Gymnocalycium gibbosum', 
        'Gymnocalycium horstii', 
        'Gymnocalycium hossei', 
        'Gymnocalycium hybopleurum', 
        'Gymnocalycium hyptiacanthum', 
        'Gymnocalycium kieslingii', 
        'Gymnocalycium kroenleinii', 
        'Gymnocalycium kuehhasii', 
        'Gymnocalycium leptanthum', 
        'Gymnocalycium marsoneri', 
        'Gymnocalycium mazanense', 
        'Gymnocalycium megatae', 
        'Gymnocalycium mesopotamicum', 
        'Gymnocalycium mihanovichii', 
        'Gymnocalycium monvillei', 
        'Gymnocalycium morroense', 
        'Gymnocalycium mostii', 
        'Gymnocalycium mucidum', 
        'Gymnocalycium neuhuberi', 
        'Gymnocalycium ochoterenae', 
        'Gymnocalycium oenanthemum', 
        'Gymnocalycium paediophilum', 
        'Gymnocalycium paraguayense', 
        'Gymnocalycium parvulum', 
        'Gymnocalycium pflanzii', 
        'Gymnocalycium pugionacanthum', 
        'Gymnocalycium quehlianum', 
        'Gymnocalycium ragonesii', 
        'Gymnocalycium reductum', 
        'Gymnocalycium rhodantherum', 
        'Gymnocalycium ritterianum', 
        'Gymnocalycium robustum', 
        'Gymnocalycium saglionis', 
        'Gymnocalycium sanluisense', 
        'Gymnocalycium schickendantzii', 
        'Gymnocalycium schroederianum', 
        'Gymnocalycium spegazzinii', 
        'Gymnocalycium stellatum', 
        'Gymnocalycium striglianum', 
        'Gymnocalycium stuckertii', 
        'Gymnocalycium taningaense', 
        'Gymnocalycium uebelmannianum', 
        'Gymnocalycium valnicekianum', 
        'Gymnocalycium villamercedense', 
        'Gymnocalycium volskyi', 
        'Haageocereus acranthus', 
        'Haageocereus australis', 
        'Haageocereus chilensis', 
        'Haageocereus comosus', 
        'Haageocereus decumbens', 
        'Haageocereus pacalaensis', 
        'Haageocereus platinospinus', 
        'Haageocereus pseudomelanostele', 
        'Haageocereus seticeps', 
        'Haageocereus tenuis', 
        'Haageocereus versicolor', 
        'Haagespostoa albisetata', 
        'Haagespostoa climaxantha', 
        'Haagespostoa mirabilis', 
        'Hariota salicornoides', 
        'Harrisia adscendens', 
        'Harrisia bonplandii', 
        'Harrisia brookii', 
        'Harrisia caymanensis', 
        'Harrisia divaricata', 
        'Harrisia earlei', 
        'Harrisia eriophora', 
        'Harrisia fernowii', 
        'Harrisia fragrans', 
        'Harrisia gracilis', 
        'Harrisia martinii', 
        'Harrisia pomanensis', 
        'Harrisia portoricensis', 
        'Harrisia regelii', 
        'Harrisia taetra', 
        'Harrisia tetracantha', 
        'Harrisia tortuosa', 
        'Harrisinopsis jusbertii', 
        'Hatiora cylindrica', 
        'Hatiora epiphylloides', 
        'Hatiora gaertneri', 
        'Hatiora graeseri', 
        'Hatiora herminiae', 
        'Hatiora rosea', 
        'Hatiora salicornioides', 
        'Hatiora saluginoides', 
        'Heliocereus jenkinsonii', 
        'Hylocereus intermedius', 
        'Isolatocereus dumortieri', 
        'Jasminocereus thouarsii', 
        'Kadenicarpus horripilus', 
        'Kadenicarpus pseudomacrochele', 
        'Kimnachia ramulosa', 
        'Lasiocereus fulvus', 
        'Lasiocereus rupicola', 
        'Leocereus bahiensis', 
        'Lepismium aculeatum', 
        'Lepismium cruciforme', 
        'Lepismium houlletianum', 
        'Lepismium lorentzianum', 
        'Lepismium lumbricoides', 
        'Lepismium warmingianum', 
        'Leptocereus arboreus', 
        'Leptocereus assurgens', 
        'Leptocereus carinatus', 
        'Leptocereus grantianus', 
        'Leptocereus leonii', 
        'Leptocereus nudiflorus', 
        'Leptocereus paniculatus', 
        'Leptocereus quadricostatus', 
        'Leptocereus scopulophilus', 
        'Leptocereus sylvestris', 
        'Leptocereus undulosus', 
        'Leptocereus velozianus', 
        'Leptocereus weingartianus', 
        'Leptocereus wrightii', 
        'Leuchtenbergia principis', 
        'Lophophora diffusa', 
        'Lophophora williamsii', 
        'Lymanbensonia brevispina', 
        'Lymanbensonia incachacana', 
        'Lymanbensonia micrantha', 
        'Maihuenia patagonica', 
        'Maihuenia poeppigii', 
        'Maihueniopsis archiconoidea', 
        'Maihueniopsis atacamensis', 
        'Maihueniopsis camachoi', 
        'Maihueniopsis colorea', 
        'Maihueniopsis crassispina', 
        'Maihueniopsis darwinii', 
        'Maihueniopsis domeykoensis', 
        'Maihueniopsis glochidiata', 
        'Maihueniopsis glomerata', 
        'Maihueniopsis grandiflora', 
        'Maihueniopsis hickenii', 
        'Maihueniopsis minuta', 
        'Maihueniopsis ovata', 
        'Maihueniopsis platyacantha', 
        'Maihueniopsis rahmeri', 
        'Maihueniopsis wagenknechtii', 
        'Mammillaria albicans', 
        'Mammillaria albicoma', 
        'Mammillaria albiflora', 
        'Mammillaria albilanata', 
        'Mammillaria anniana', 
        'Mammillaria armillata', 
        'Mammillaria atrorubra', 
        'Mammillaria aureilanata', 
        'Mammillaria backebergiana', 
        'Mammillaria barbata', 
        'Mammillaria baumii', 
        'Mammillaria beneckei', 
        'Mammillaria berkiana', 
        'Mammillaria blossfeldiana', 
        'Mammillaria bocasana', 
        'Mammillaria bocensis', 
        'Mammillaria boelderliana', 
        'Mammillaria bombycina', 
        'Mammillaria boolii', 
        'Mammillaria brandegeei', 
        'Mammillaria capensis', 
        'Mammillaria carmenae', 
        'Mammillaria carnea', 
        'Mammillaria carretii', 
        'Mammillaria coahuilensis', 
        'Mammillaria columbiana', 
        'Mammillaria compressa', 
        'Mammillaria crinita', 
        'Mammillaria crucigera', 
        'Mammillaria decipiens', 
        'Mammillaria deherdtiana', 
        'Mammillaria deliusiana', 
        'Mammillaria densispina', 
        'Mammillaria dioica', 
        'Mammillaria discolor', 
        'Mammillaria dixanthocentron', 
        'Mammillaria duoformis', 
        'Mammillaria duwei', 
        'Mammillaria ekmanii', 
        'Mammillaria elongata', 
        'Mammillaria eriacantha', 
        'Mammillaria erythrosperma', 
        'Mammillaria euchlora', 
        'Mammillaria evermanniana', 
        'Mammillaria fellneri', 
        'Mammillaria fittkaui', 
        'Mammillaria flavescens', 
        'Mammillaria formosa', 
        'Mammillaria fulvolanata', 
        'Mammillaria gasseriana', 
        'Mammillaria geminispina', 
        'Mammillaria gigantea', 
        'Mammillaria glassii', 
        'Mammillaria glauca', 
        'Mammillaria goodrichii', 
        'Mammillaria goodridgei', 
        'Mammillaria goodridgii', 
        'Mammillaria grahamii', 
        'Mammillaria grandis', 
        'Mammillaria grusonii', 
        'Mammillaria guameri', 
        'Mammillaria guelzowiana', 
        'Mammillaria guerreronis', 
        'Mammillaria guillauminiana', 
        'Mammillaria haageana', 
        'Mammillaria hahniana', 
        'Mammillaria halbingeri', 
        'Mammillaria halei', 
        'Mammillaria hermosana', 
        'Mammillaria hernandezii', 
        'Mammillaria herrerae', 
        'Mammillaria heteracantha', 
        'Mammillaria heyderi', 
        'Mammillaria huitzilopochtli', 
        'Mammillaria humboldtii', 
        'Mammillaria huntiana', 
        'Mammillaria hutchisoniana', 
        'Mammillaria insularis', 
        'Mammillaria jaliscana', 
        'Mammillaria johnstonii', 
        'Mammillaria joossensiana', 
        'Mammillaria karwinskiana', 
        'Mammillaria klissingiana', 
        'Mammillaria knippeliana', 
        'Mammillaria kraehenbuehlii', 
        'Mammillaria lasiacantha', 
        'Mammillaria laui', 
        'Mammillaria lenta', 
        'Mammillaria leucantha', 
        'Mammillaria longiflora', 
        'Mammillaria longimamma', 
        'Mammillaria luethyi', 
        'Mammillaria magnifica', 
        'Mammillaria magnimamma', 
        'Mammillaria mainae', 
        'Mammillaria mainiae', 
        'Mammillaria mamillaria', 
        'Mammillaria mammillaris', 
        'Mammillaria marcosii', 
        'Mammillaria marksiana', 
        'Mammillaria mathildae', 
        'Mammillaria matudae', 
        'Mammillaria mazatlanensis', 
        'Mammillaria melaleuca', 
        'Mammillaria melanocentra', 
        'Mammillaria mercadensis', 
        'Mammillaria meyranii', 
        'Mammillaria microhelia', 
        'Mammillaria microthele', 
        'Mammillaria mieheana', 
        'Mammillaria moelleriana', 
        'Mammillaria morganiana', 
        'Mammillaria muehlenpfordtii', 
        'Mammillaria multidigitata', 
        'Mammillaria mystax', 
        'Mammillaria nana', 
        'Mammillaria napina', 
        'Mammillaria neopalmeri', 
        'Mammillaria nivosa', 
        'Mammillaria nunezii', 
        'Mammillaria orcuttii', 
        'Mammillaria ortiz-rubiona', 
        'Mammillaria oteroi', 
        'Mammillaria palmeri', 
        'Mammillaria parkinsonii', 
        'Mammillaria pectinifera', 
        'Mammillaria peninsularis', 
        'Mammillaria pennispinosa', 
        'Mammillaria perbella', 
        'Mammillaria pertinata', 
        'Mammillaria petrophila', 
        'Mammillaria petterssonii', 
        'Mammillaria phitauiana', 
        'Mammillaria picta', 
        'Mammillaria pilispina', 
        'Mammillaria plumosa', 
        'Mammillaria polyedra', 
        'Mammillaria polythele', 
        'Mammillaria pondii', 
        'Mammillaria poselgeri', 
        'Mammillaria pottsii', 
        'Mammillaria pringlei', 
        'Mammillaria prolifera', 
        'Mammillaria purpurea', 
        'Mammillaria rekoi', 
        'Mammillaria rettigiana', 
        'Mammillaria rhodantha', 
        'Mammillaria rosea', 
        'Mammillaria rubidula', 
        'Mammillaria saboae', 
        'Mammillaria saltillensis', 
        'Mammillaria sanchez-mejoradae', 
        'Mammillaria sartorii', 
        'Mammillaria schiedeana', 
        'Mammillaria schumannii', 
        'Mammillaria schwarzii', 
        'Mammillaria scrippsiana', 
        'Mammillaria seidelii', 
        'Mammillaria sempervivi', 
        'Mammillaria senilis', 
        'Mammillaria sinforosensis', 
        'Mammillaria sinistrohamata', 
        'Mammillaria sonorensis', 
        'Mammillaria spectabilis', 
        'Mammillaria sphacelata', 
        'Mammillaria sphaerica', 
        'Mammillaria spinosissima', 
        'Mammillaria standleyi', 
        'Mammillaria supertexta', 
        'Mammillaria surculosa', 
        'Mammillaria tayloriorum', 
        'Mammillaria tenuis', 
        'Mammillaria tetrancistra', 
        'Mammillaria theresae', 
        'Mammillaria thomasii', 
        'Mammillaria thornberi', 
        'Mammillaria tonalensis', 
        'Mammillaria uncinata', 
        'Mammillaria variaculeata', 
        'Mammillaria varicolor', 
        'Mammillaria varieaculeata', 
        'Mammillaria vetula', 
        'Mammillaria villifera', 
        'Mammillaria voburnensis', 
        'Mammillaria wagneriana', 
        'Mammillaria wegenerii', 
        'Mammillaria weingartiana', 
        'Mammillaria wiesingeri', 
        'Mammillaria winterae', 
        'Mammillaria wrightii', 
        'Mammillaria xaltianguensis', 
        'Mammillaria zeilmanniana', 
        'Mammillaria zephyranthoides', 
        'Mammillaria zublerae', 
        'Mammilloydia candida', 
        'Matucana aurantiaca', 
        'Matucana aureiflora', 
        'Matucana formosa', 
        'Matucana haynei', 
        'Matucana huagalensis', 
        'Matucana intertexta', 
        'Matucana krahnii', 
        'Matucana madisoniorum', 
        'Matucana mirabilis', 
        'Matucana oreodoxa', 
        'Matucana paucicostata', 
        'Matucana pujupatii', 
        'Matucana ritteri', 
        'Matucana tuberculata', 
        'Matucana weberbaueri', 
        'Melocactus acunai', 
        'Melocactus albicephalus', 
        'Melocactus andinus', 
        'Melocactus azureus', 
        'Melocactus bahiensis', 
        'Melocactus bellavistensis', 
        'Melocactus broadwayi', 
        'Melocactus caroli-linnaei', 
        'Melocactus concinnus', 
        'Melocactus conoideus', 
        'Melocactus curvispinus', 
        'Melocactus deinacanthus', 
        'Melocactus ernestii', 
        'Melocactus estevesii', 
        'Melocactus ferreophilus', 
        'Melocactus glaucescens', 
        'Melocactus harlowii', 
        'Melocactus heimenii', 
        'Melocactus horridus', 
        'Melocactus inconcinnus', 
        'Melocactus intortus', 
        'Melocactus lanssensianus', 
        'Melocactus lemairei', 
        'Melocactus levitestatus', 
        'Melocactus macracanthos', 
        'Melocactus matanzanus', 
        'Melocactus mazelianus', 
        'Melocactus neryi', 
        'Melocactus oreas', 
        'Melocactus pachyacanthus', 
        'Melocactus pachycephalus', 
        'Melocactus paucispinus', 
        'Melocactus peruvianus', 
        'Melocactus salvadorensis', 
        'Melocactus schatzlii', 
        'Melocactus sergipensis', 
        'Melocactus smithii', 
        'Melocactus violaceus', 
        'Melocactus zehntneri', 
        'Micranthocereus albicephalus', 
        'Micranthocereus auriazureus', 
        'Micranthocereus dolichospermaticus', 
        'Micranthocereus estevesii', 
        'Micranthocereus flaviflorus', 
        'Micranthocereus oliveirae', 
        'Micranthocereus polyanthus', 
        'Micranthocereus purpureus', 
        'Micranthocereus streckeri', 
        'Micranthocereus violaciflorus', 
        'Micropuntia pulchella', 
        'Mila caespitosa', 
        'Miqueliopuntia miquelii', 
        'Myrtgerocactus lindsayi', 
        'Myrtillocactus cochal', 
        'Myrtillocactus eichlamii', 
        'Myrtillocactus geometrizans', 
        'Myrtillocactus schenckii', 
        'Neobuxbaumia euphorbioides', 
        'Neobuxbaumia laui', 
        'Neobuxbaumia macrocephala', 
        'Neobuxbaumia mezcalaensis', 
        'Neobuxbaumia polylopha', 
        'Neobuxbaumia scoparia', 
        'Neobuxbaumia squamulosa', 
        'Neobuxbaumia tetetzo', 
        'Neolloydia conoidea', 
        'Neolloydia conoides', 
        'Neolloydia matehualensis', 
        'Neomammillaria crodidata', 
        'Neomammillaria winteriae', 
        'Neoporteria rapifera', 
        'Neoraimondia arequipensis', 
        'Neoraimondia herzogiana', 
        'Neowerdermannia chilensis', 
        'Neowerdermannia vorwerkii', 
        'Nopalea cochenillifera', 
        'Nopalea guatemalensis', 
        'Notocactus notabilis', 
        'Notocactus velenovskyi', 
        'Obregonia denegrii', 
        'Opuntia acaulis', 
        'Opuntia aciculata', 
        'Opuntia aequatorialis', 
        'Opuntia albicarpa', 
        'Opuntia alko-tuna', 
        'Opuntia amarilla', 
        'Opuntia anacantha', 
        'Opuntia andersonii', 
        'Opuntia arcei', 
        'Opuntia arechavaletai', 
        'Opuntia assumptionis', 
        'Opuntia atrispina', 
        'Opuntia auberi', 
        'Opuntia aurantiaca', 
        'Opuntia aurea', 
        'Opuntia aureispina', 
        'Opuntia bakeri', 
        'Opuntia basilaris', 
        'Opuntia bisetosa', 
        'Opuntia boldinghii', 
        'Opuntia borinquensis', 
        'Opuntia bravoana', 
        'Opuntia caracassana', 
        'Opuntia carstenii', 
        'Opuntia cespitosa', 
        'Opuntia chaffeyi', 
        'Opuntia chata', 
        'Opuntia chiangiana', 
        'Opuntia chisosensis', 
        'Opuntia chlorotica', 
        'Opuntia clarkiorum', 
        'Opuntia cochenillifera', 
        'Opuntia cochinera', 
        'Opuntia colubrina', 
        'Opuntia columbiana', 
        'Opuntia conjungens', 
        'Opuntia crystalenia', 
        'Opuntia cubensis', 
        'Opuntia curassavica', 
        'Opuntia curvispina', 
        'Opuntia cyanella', 
        'Opuntia deamii', 
        'Opuntia debreczyi', 
        'Opuntia decumbens', 
        'Opuntia dejecta', 
        'Opuntia demissa', 
        'Opuntia depressa', 
        'Opuntia diploursina', 
        'Opuntia discolor', 
        'Opuntia diversispina', 
        'Opuntia domingensis', 
        'Opuntia edwardsii', 
        'Opuntia effulgia', 
        'Opuntia elata', 
        'Opuntia elatior', 
        'Opuntia elisae', 
        'Opuntia elizondoana', 
        'Opuntia ellisiana', 
        'Opuntia engelmannii', 
        'Opuntia excelsa', 
        'Opuntia feracantha', 
        'Opuntia feroacantha', 
        'Opuntia ficus-indica', 
        'Opuntia fragilis', 
        'Opuntia fuliginosa', 
        'Opuntia galapageia', 
        'Opuntia gallegiana', 
        'Opuntia glaucophylla', 
        'Opuntia gosseliniana', 
        'Opuntia greenei', 
        'Opuntia grosseiana', 
        'Opuntia hanburyana', 
        'Opuntia heacockae', 
        'Opuntia hitchcockii', 
        'Opuntia hondurensis', 
        'Opuntia horstii', 
        'Opuntia howeyi', 
        'Opuntia huajuapensis', 
        'Opuntia humifusa', 
        'Opuntia hybr', 
        'Opuntia hyptiacantha', 
        'Opuntia inaperta', 
        'Opuntia ithypetala', 
        'Opuntia lagunae', 
        'Opuntia lasiacantha', 
        'Opuntia leoglossa', 
        'Opuntia leucotricha', 
        'Opuntia littoralis', 
        'Opuntia lucayana', 
        'Opuntia macrocentra', 
        'Opuntia macrorhiza', 
        'Opuntia megapotamica', 
        'Opuntia megarrhiza', 
        'Opuntia microcarpa', 
        'Opuntia microdasys', 
        'Opuntia miquelii', 
        'Opuntia monacantha', 
        'Opuntia occidentalis', 
        'Opuntia olmeca', 
        'Opuntia opuntia', 
        'Opuntia orbiculata', 
        'Opuntia oricola', 
        'Opuntia ottonis', 
        'Opuntia parviclada', 
        'Opuntia penicilligera', 
        'Opuntia perotensis', 
        'Opuntia phaeacantha', 
        'Opuntia pilifera', 
        'Opuntia pinkavae', 
        'Opuntia pisciformis', 
        'Opuntia pittieri', 
        'Opuntia polyacantha', 
        'Opuntia pottsii', 
        'Opuntia preciadoae', 
        'Opuntia puberula', 
        'Opuntia pubescens', 
        'Opuntia pusilla', 
        'Opuntia pycnacantha', 
        'Opuntia pycnantha', 
        'Opuntia quimilo', 
        'Opuntia quitensis', 
        'Opuntia repens', 
        'Opuntia rioplatense', 
        'Opuntia robinsonii', 
        'Opuntia robusta', 
        'Opuntia rooneyi', 
        'Opuntia rufida', 
        'Opuntia sanguinea', 
        'Opuntia scheeri', 
        'Opuntia schumannii', 
        'Opuntia senilis', 
        'Opuntia setispina', 
        'Opuntia soederstromiana', 
        'Opuntia spinosibacca', 
        'Opuntia spinulifera', 
        'Opuntia stenarthra', 
        'Opuntia stenopetala', 
        'Opuntia streptacantha', 
        'Opuntia stricta', 
        'Opuntia strigil', 
        'Opuntia sulphurea', 
        'Opuntia tapona', 
        'Opuntia taylorii', 
        'Opuntia tehuacana', 
        'Opuntia tehuantepecana', 
        'Opuntia tezontepecana', 
        'Opuntia tomentosa', 
        'Opuntia triacantha', 
        'Opuntia vaseyi', 
        'Opuntia velutina', 
        'Opuntia virens', 
        'Opuntia vulgaris', 
        'Opuntia wilcoxii', 
        'Opuntia wootonii', 
        'Opuntia zacuapanensis', 
        'Oreocereus australis', 
        'Oreocereus celsianus', 
        'Oreocereus doelzianus', 
        'Oreocereus hempelianus', 
        'Oreocereus leucotrichus', 
        'Oreocereus pseudofossulatus', 
        'Oreocereus tacnaensis', 
        'Oreocereus trollii', 
        'Oreocereus variicolor', 
        'Oroya borchersii', 
        'Oroya peruviana', 
        'Ortegocactus macdougallii', 
        'Pacherocactus orcuttii', 
        'Pachycereus fulviceps', 
        'Pachycereus gatesii', 
        'Pachycereus gaumeri', 
        'Pachycereus grandis', 
        'Pachycereus hollianus', 
        'Pachycereus lepidanthus', 
        'Pachycereus marginatus', 
        'Pachycereus militaris', 
        'Pachycereus pecten-aboriginum', 
        'Pachycereus pringlei', 
        'Pachycereus schottii', 
        'Pachycereus tepamo', 
        'Pachycereus weberi', 
        'Parodia alacriportana', 
        'Parodia allosiphon', 
        'Parodia arnostiana', 
        'Parodia aureicentra', 
        'Parodia ayopayana', 
        'Parodia buiningii', 
        'Parodia carambeiensis', 
        'Parodia chrysacanthion', 
        'Parodia columnaris', 
        'Parodia comarapana', 
        'Parodia commutans', 
        'Parodia concinna', 
        'Parodia crassigibba', 
        'Parodia curvispina', 
        'Parodia erinacea', 
        'Parodia erubescens', 
        'Parodia fusca', 
        'Parodia gaucha', 
        'Parodia gibbulosoides', 
        'Parodia haselbergii', 
        'Parodia hausteiniana', 
        'Parodia hegeri', 
        'Parodia herteri', 
        'Parodia horstii', 
        'Parodia langsdorfii', 
        'Parodia larapuntensis', 
        'Parodia leninghausii', 
        'Parodia linkii', 
        'Parodia maassii', 
        'Parodia magnifica', 
        'Parodia mammulosa', 
        'Parodia microsperma', 
        'Parodia mueller-melchersii', 
        'Parodia muricata', 
        'Parodia neoarechavaletae', 
        'Parodia neohorstii', 
        'Parodia nigrispina', 
        'Parodia nivosa', 
        'Parodia nothorauschii', 
        'Parodia ocampoi', 
        'Parodia otaviana', 
        'Parodia ottonis', 
        'Parodia oxycostata', 
        'Parodia penicellata', 
        'Parodia penicillata', 
        'Parodia pilayaensis', 
        'Parodia prestoensis', 
        'Parodia procera', 
        'Parodia rechensis', 
        'Parodia ritteri', 
        'Parodia rosarioana', 
        'Parodia rudibuenekeri', 
        'Parodia schumanniana', 
        'Parodia schwebsiana', 
        'Parodia scopa', 
        'Parodia sellowii', 
        'Parodia stockingeri', 
        'Parodia stuemeri', 
        'Parodia submammulosa', 
        'Parodia subterranea', 
        'Parodia tabularis', 
        'Parodia taratensis', 
        'Parodia tenuicylindrica', 
        'Parodia tuberculata', 
        'Parodia turbinata', 
        'Parodia turecekiana', 
        'Parodia warasii', 
        'Parodia werdermanniana', 
        'Pediocactus bradyi', 
        'Pediocactus knowltonii', 
        'Pediocactus nigrispinus', 
        'Pediocactus paradinei', 
        'Pediocactus peeblesianus', 
        'Pediocactus sileri', 
        'Pediocactus simpsonii', 
        'Pelecyphora aselliformis', 
        'Pelecyphora strobiliformis', 
        'Peniocereus greggii', 
        'Peniocereus guatemalensis', 
        'Peniocereus johnstonii', 
        'Peniocereus lazaro-cardenasii', 
        'Peniocereus marianus', 
        'Peniocereus marnierianus', 
        'Peniocereus serpentinus', 
        'Peniocereus striatus', 
        'Peniocereus viperinus', 
        'Peniocereus zopilotensis', 
        'Pereskia aculeata', 
        'Pereskia aureiflora', 
        'Pereskia bahiensis', 
        'Pereskia bleo', 
        'Pereskia diaz-romeroana', 
        'Pereskia grandifolia', 
        'Pereskia guamacho', 
        'Pereskia horrida', 
        'Pereskia kellermannii', 
        'Pereskia lychnidiflora', 
        'Pereskia marcanoi', 
        'Pereskia nemorosa', 
        'Pereskia portulacifolia', 
        'Pereskia quisqueyana', 
        'Pereskia sacharosa', 
        'Pereskia stenantha', 
        'Pereskia violacea', 
        'Pereskia weberiana', 
        'Pereskia zinniiflora', 
        'Pereskiopsis aquosa', 
        'Pereskiopsis blakeana', 
        'Pereskiopsis diguetii', 
        'Pereskiopsis kellermanii', 
        'Pereskiopsis porteri', 
        'Pereskiopsis rotundifolia', 
        'Pfeiffera asuntapatensis', 
        'Pfeiffera boliviana', 
        'Pfeiffera crenata', 
        'Pfeiffera ianthothele', 
        'Pfeiffera miyagawae', 
        'Pfeiffera monacantha', 
        'Pfeiffera paraganiensis', 
        'Phyllocactus russellianus', 
        'Pierrebraunia bahiensis', 
        'Pierrebraunia eddie-estevesii', 
        'Pilosocereus alensis', 
        'Pilosocereus arrabidae', 
        'Pilosocereus aureispinus', 
        'Pilosocereus aurisetus', 
        'Pilosocereus azulensis', 
        'Pilosocereus barbadensis', 
        'Pilosocereus bohlei', 
        'Pilosocereus brasiliensis', 
        'Pilosocereus catingicola', 
        'Pilosocereus chrysacanthus', 
        'Pilosocereus chrysostele', 
        'Pilosocereus collinsii', 
        'Pilosocereus colombianus', 
        'Pilosocereus curtisii', 
        'Pilosocereus densiareolatus', 
        'Pilosocereus diersianus', 
        'Pilosocereus flavipulvinatus', 
        'Pilosocereus flexibilispinus', 
        'Pilosocereus floccosus', 
        'Pilosocereus fulvilanatus', 
        'Pilosocereus glaucochrous', 
        'Pilosocereus hermii', 
        'Pilosocereus jauruensis', 
        'Pilosocereus juaruensis', 
        'Pilosocereus lanuginosus', 
        'Pilosocereus leucocephalus', 
        'Pilosocereus machrisii', 
        'Pilosocereus magnificus', 
        'Pilosocereus moritzianus', 
        'Pilosocereus multicostatus', 
        'Pilosocereus occultiflorus', 
        'Pilosocereus oligolepis', 
        'Pilosocereus pachycladus', 
        'Pilosocereus parvus', 
        'Pilosocereus pentaedrophorus', 
        'Pilosocereus piauhyensis', 
        'Pilosocereus polygonus', 
        'Pilosocereus purpusii', 
        'Pilosocereus pusillibaccatus', 
        'Pilosocereus quadricentralis', 
        'Pilosocereus robinii', 
        'Pilosocereus royenii', 
        'Pilosocereus splendidus', 
        'Pilosocereus subsimilis', 
        'Pilosocereus tillianus', 
        'Pilosocereus ulei', 
        'Pilosocereus vilaboensis', 
        'Polaskia chende', 
        'Polaskia chichipe', 
        'Praecereus euchlorus', 
        'Praecereus saxicola', 
        'Pseudorhipsalis acuminata', 
        'Pseudorhipsalis alata', 
        'Pseudorhipsalis amazonica', 
        'Pseudorhipsalis himantoclada', 
        'Pseudorhipsalis lankesteri', 
        'Pterocactus araucanus', 
        'Pterocactus australis', 
        'Pterocactus fischeri', 
        'Pterocactus gonjianii', 
        'Pterocactus hickenii', 
        'Pterocactus megliolii', 
        'Pterocactus neuquensis', 
        'Pterocactus reticulatus', 
        'Pterocactus tuberosus', 
        'Pterocactus valentinii', 
        'Puna clavarioides', 
        'Puna subterranea', 
        'Punotia lagopus', 
        'Pygmaeocereus bieblii', 
        'Pygmaeocereus bylesianus', 
        'Quiabentia verticillata', 
        'Quiabentia zehntneri', 
        'Rapicactus beguinii', 
        'Rapicactus mandragora', 
        'Rapicactus subterraneus', 
        'Rapicactus zaragosae', 
        'Rauhocereus riosaniensis', 
        'Rebutia borealis', 
        'Rebutia cintia', 
        'Rebutia fidana', 
        'Rebutia fulviseta', 
        'Rebutia marsoneri', 
        'Rebutia minuscula', 
        'Rebutia spegazziana', 
        'Rhipsalis agudoensis', 
        'Rhipsalis aurea', 
        'Rhipsalis barthlottii', 
        'Rhipsalis boliviana', 
        'Rhipsalis burchellii', 
        'Rhipsalis campos-portoana', 
        'Rhipsalis carnosa', 
        'Rhipsalis cereoides', 
        'Rhipsalis cereuscula', 
        'Rhipsalis clavata', 
        'Rhipsalis crispata', 
        'Rhipsalis cuneata', 
        'Rhipsalis dissimilis', 
        'Rhipsalis elliptica', 
        'Rhipsalis ewaldiana', 
        'Rhipsalis flagelliformis', 
        'Rhipsalis floccosa', 
        'Rhipsalis goebeliana', 
        'Rhipsalis grandiflora', 
        'Rhipsalis hoelleri', 
        'Rhipsalis juengeri', 
        'Rhipsalis lindbergiana', 
        'Rhipsalis macahensis', 
        'Rhipsalis mesembryanthemoides', 
        'Rhipsalis mesembryanthoides', 
        'Rhipsalis micrantha', 
        'Rhipsalis neves-armondii', 
        'Rhipsalis oblonga', 
        'Rhipsalis occidentalis', 
        'Rhipsalis olivifera', 
        'Rhipsalis ormindoi', 
        'Rhipsalis pacheco-leonis', 
        'Rhipsalis pachyptera', 
        'Rhipsalis paradoxa', 
        'Rhipsalis parasitica', 
        'Rhipsalis pentaptera', 
        'Rhipsalis pilocarpa', 
        'Rhipsalis pulchra', 
        'Rhipsalis puniceodiscus', 
        'Rhipsalis russellii', 
        'Rhipsalis sulcata', 
        'Rhipsalis teres', 
        'Rhipsalis triangularis', 
        'Rhipsalis trigona', 
        'Rimacactus laui', 
        'Salmiopuntia salmiana', 
        'Samaipaticereus corroanus', 
        'Schlumbergera buckleyi', 
        'Schlumbergera exotica', 
        'Schlumbergera kautskyi', 
        'Schlumbergera microsphaerica', 
        'Schlumbergera opuntioides', 
        'Schlumbergera orssichiana', 
        'Schlumbergera reginae', 
        'Schlumbergera russeliana', 
        'Schlumbergera truncata', 
        'Sclerocactus brevihamatus', 
        'Sclerocactus erectocentrus', 
        'Sclerocactus glaucus', 
        'Sclerocactus intertextus', 
        'Sclerocactus johnsonii', 
        'Sclerocactus mariposensis', 
        'Sclerocactus mesae-verdae', 
        'Sclerocactus papyracanthus', 
        'Sclerocactus parviflorus', 
        'Sclerocactus pinkavanus', 
        'Sclerocactus polyancistrus', 
        'Sclerocactus pubispinus', 
        'Sclerocactus scheerii', 
        'Sclerocactus spinosior', 
        'Sclerocactus uncinatus', 
        'Sclerocactus unguispinus', 
        'Sclerocactus warnockii', 
        'Sclerocactus whipplei', 
        'Sclerocactus wrightiae', 
        'Selenicereus anthonyanus', 
        'Selenicereus atropilosus', 
        'Selenicereus calcaratus', 
        'Selenicereus chrysocardium', 
        'Selenicereus costaricensis', 
        'Selenicereus dorschianus', 
        'Selenicereus escuintlensis', 
        'Selenicereus extensus', 
        'Selenicereus grandiflorus', 
        'Selenicereus guatemalensis', 
        'Selenicereus hamatus', 
        'Selenicereus inermis', 
        'Selenicereus megalanthus', 
        'Selenicereus minutiflorus', 
        'Selenicereus monacanthus', 
        'Selenicereus murrillii', 
        'Selenicereus nelsonii', 
        'Selenicereus ocamponis', 
        'Selenicereus pteranthus', 
        'Selenicereus purpusii', 
        'Selenicereus setaceus', 
        'Selenicereus spinulosus', 
        'Selenicereus stenopterus', 
        'Selenicereus triangularis', 
        'Selenicereus tricae', 
        'Selenicereus undatus', 
        'Selenicereus vagans', 
        'Selenicereus validus', 
        'Stenocactus coptonogonus', 
        'Stenocactus crispatus', 
        'Stenocactus heteracanthus', 
        'Stenocactus multicostatus', 
        'Stenocactus obvallatus', 
        'Stenocactus ochoterenanus', 
        'Stenocactus ochoterenianus', 
        'Stenocactus phyllacanthus', 
        'Stenocactus sulphureus', 
        'Stenocactus vaupelianus', 
        'Stenocereus alamosensis', 
        'Stenocereus aragonii', 
        'Stenocereus beneckei', 
        'Stenocereus chacalapensis', 
        'Stenocereus chrysocarpus', 
        'Stenocereus eichlamii', 
        'Stenocereus eruca', 
        'Stenocereus fimbriatus', 
        'Stenocereus fricii', 
        'Stenocereus griseus', 
        'Stenocereus gummosus', 
        'Stenocereus heptagonus', 
        'Stenocereus huastecorum', 
        'Stenocereus humilis', 
        'Stenocereus kerberi', 
        'Stenocereus martinezii', 
        'Stenocereus montanus', 
        'Stenocereus pruinosus', 
        'Stenocereus queretaroensis', 
        'Stenocereus quevedonis', 
        'Stenocereus standleyi', 
        'Stenocereus stellatus', 
        'Stenocereus thurberi', 
        'Stenocereus treleasei', 
        'Stenocereus zopilotensis', 
        'Stephanocereus leucostele', 
        'Stephanocereus luetzelburgii', 
        'Stetsonia coryne', 
        'Strombocactus corregidorae', 
        'Strombocactus disciformis', 
        'Strophocactus brasiliensis', 
        'Strophocactus sicariguensis', 
        'Strophocactus wittii', 
        'Tacinga braunii', 
        'Tacinga funalis', 
        'Tacinga inamoena', 
        'Tacinga lilae', 
        'Tacinga palmadora', 
        'Tacinga quipa', 
        'Tacinga saxatilis', 
        'Tacinga werneri', 
        'Tephrocactus alexanderi', 
        'Tephrocactus aoracanthus', 
        'Tephrocactus articulatus', 
        'Tephrocactus bonnieae', 
        'Tephrocactus halophilus', 
        'Tephrocactus molinensis', 
        'Tephrocactus nigrispinus', 
        'Tephrocactus recurvatus', 
        'Tephrocactus verschaffeltii', 
        'Tephrocactus weberi', 
        'Thelocactus bicolor', 
        'Thelocactus bueckii', 
        'Thelocactus buekii', 
        'Thelocactus conothelos', 
        'Thelocactus hastifer', 
        'Thelocactus hexaedrophorus', 
        'Thelocactus lausseri', 
        'Thelocactus leucacanthus', 
        'Thelocactus leucanthus', 
        'Thelocactus lophothele', 
        'Thelocactus macdowellii', 
        'Thelocactus setispinus', 
        'Thelocactus tepelmemensis', 
        'Thelocactus tulensis', 
        'Torreycactus conothele', 
        'Trichocereus huanucoensis', 
        'Trichocereus johnsonii', 
        'Trichocereus macrogonus', 
        'Trichocereus spinibarbis', 
        'Trichocereus tarikensis', 
        'Trichoechinopsis imperialis', 
        'Trichomoza roseiflora', 
        'Tunilla chilensis', 
        'Tunilla corrugata', 
        'Tunilla erectoclada', 
        'Tunilla soehrensii', 
        'Tunilla tilcarensis', 
        'Turbinicarpus alonsoi', 
        'Turbinicarpus gielsdorfianus', 
        'Turbinicarpus heliae', 
        'Turbinicarpus hoferi', 
        'Turbinicarpus laui', 
        'Turbinicarpus lophophoroides', 
        'Turbinicarpus mombergeri', 
        'Turbinicarpus nikolae', 
        'Turbinicarpus pseudopectinatus', 
        'Turbinicarpus roseiflorus', 
        'Turbinicarpus saueri', 
        'Turbinicarpus schmiedickeanus', 
        'Turbinicarpus swobodae', 
        'Turbinicarpus valdezianus', 
        'Turbinicarpus viereckii', 
        'Uebelmannia buiningii', 
        'Uebelmannia gummifera', 
        'Uebelmannia pectinifera', 
        'Weberbauerocereus albus', 
        'Weberbauerocereus callanus', 
        'Weberbauerocereus cephalomacrostibas', 
        'Weberbauerocereus churinensis', 
        'Weberbauerocereus cuzcoensis', 
        'Weberbauerocereus madidiensis', 
        'Weberbauerocereus rauhii', 
        'Weberbauerocereus weberbaueri', 
        'Weberbauerocereus winterianus', 
        'Weberocereus alliodorus', 
        'Weberocereus bradei', 
        'Weberocereus frohningiorum', 
        'Weberocereus glaber', 
        'Weberocereus imitans', 
        'Weberocereus rosei', 
        'Weberocereus tonduzii', 
        'Weberocereus trichophorus', 
        'Weberocereus tunilla', 
        'Weingartia arachnites', 
        'Weingartia arenacea', 
        'Weingartia atrospinosa', 
        'Weingartia azurduyensis', 
        'Weingartia breviflora', 
        'Weingartia canigueralii', 
        'Weingartia cantargalloensis', 
        'Weingartia cardenasiana', 
        'Weingartia christiei', 
        'Weingartia confusa', 
        'Weingartia cylindrica', 
        'Weingartia fidaiana', 
        'Weingartia frey-juckeri', 
        'Weingartia glomeriseta', 
        'Weingartia heliosoides', 
        'Weingartia insperata', 
        'Weingartia juckeri', 
        'Weingartia kruegeri', 
        'Weingartia lamprochlora', 
        'Weingartia lanata', 
        'Weingartia margarethae', 
        'Weingartia mentosa', 
        'Weingartia neocumingii', 
        'Weingartia neumanniana', 
        'Weingartia oligacantha', 
        'Weingartia pirhuaniensis', 
        'Weingartia pucarensis', 
        'Weingartia pulchra', 
        'Weingartia purpurea', 
        'Weingartia roberto-vasquezii', 
        'Weingartia sedae', 
        'Weingartia slabana', 
        'Weingartia steinbachii', 
        'Weingartia tarijensis', 
        'Weingartia tiraquensis', 
        'Weingartia trojapampensis', 
        'Weingartia vasqueziana', 
        'Weingartia viridis', 
        'Wigginsia sessiflora', 
        'Wigginsia vorweckiana', 
        'Xiquexique frewenii', 
        'Xiquexique gounellei', 
        'Xiquexique tuberculatus', 
        'Yavia cryptocarpa', 
        'Yungasocereus inquisivensis', 
    ];
}

